[project]
name = "ghost-monitor"
description = "Ghost Monitor for job and system management"
dynamic = ["version"]
requires-python = ">= 3.11"
dependencies = [
  "textual>=2.1.2"
]

[build-system]
requires = ["setuptools >= 61.0", "setuptools-scm >= 8.2"]
build-backend = "setuptools.build_meta"